strategy:
  name: "Opening Range — NSXUSD"
  version: 1

parameters:
  zones:
    top_pct: 0.35 # long if price in top 35% of OR
    bottom_pct: 0.35 # short if price in bottom 35% of OR
  risk:
    stop_loss_points: 25
    take_profit_points: 75
  execution:
    one_trade_per_day: true
    allow_reentry_same_day: false
    fill_detection: "intrabar_high_low" # detect SL/TP with bar high/low
    fill_price_policy: "at_level" # fill exactly at SL/TP level
    round_to_tick: true
  capital:
    initial_usd: 100000

evaluation:
  metrics:
    - net_return
    - max_drawdown
    - win_rate
    - profit_factor
    - expectancy
    - avg_win
    - avg_loss
    - cagr
    - volatility
    - sortino
  reporting:
    save_trade_log: true
    save_equity_curve: true
